server: 
  port: 8080
    
spring:
  profiles.active: development.env
  jpa: 
    properties.jadira.usertype.autoRegisterUserTypes: true
    generate-ddl: true
    hibernate.ddl-auto: update
    hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    max-active: 8
    initial-size: 2
    max-idle: 2
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000

user.admin:
  username: admin
  password: coin@dmin

jwt.token:
  issuer: coin-manager
  secret: coin-manager
  expires: 86400

---
spring:
  profiles: development.env
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/coin_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: henhao
    platform: mysql
    database: mysql

---
spring:
  profiles: production.env
  datasource:
    platform: mysql
    url: jdbc:p6spy:mysql://127.0.0.1:3306/coin_manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: henhao
    database: mysql

---
spring:
  profiles: test.env
  datasource:
    platform: h2
    url: 'jdbc:h2:mem:coin-manager'
    username: sa
